title: "SoilWise Geopackage"
description: "SoilWise Geopackage Documentation"

url: https://soilwise-he.github.io
baseurl: /Geopackage-so

#theme: minima   # tema standard
remote_theme: pages-themes/primer@v0.6.0
#remote_theme: pages-themes/primer
#remote_theme: pages-themes/minimal@v0.2.0

# _config.yml
defaults:
  - scope:
      path: ""          # tutto il sito (o "documentation" se vuoi limitarlo)
      type: "pages"     # applica ai “pages”; usa "posts" per i post, o il nome di una collection
    values:
      layout: "default"
      author: "Andrea Lachi"
      project: "SoilWise"



# Impostazioni GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter



relative_links:
  enabled: true
  collections: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - README.md
